-- Public read RPCs: callable by signed-out and signed-in viewers.
revoke execute on function public.get_binary_final_result(uuid) from public;
revoke execute on function public.get_faction_change_events(uuid) from public;
revoke execute on function public.get_post_reaction_counts(uuid) from public;
revoke execute on function public.get_superiority_final_result(uuid) from public;
revoke execute on function public.get_topic_faction_summary(uuid) from public;
revoke execute on function public.get_topic_public_stats(uuid) from public;
revoke execute on function public.get_topic_recent_activity(uuid) from public;
revoke execute on function public.get_topic_record_summary(uuid) from public;
revoke execute on function public.get_topics_public_stats(uuid[]) from public;
revoke execute on function public.get_topics_recent_activity(uuid[]) from public;
revoke execute on function public.get_werewolf_reveal_pairs(uuid) from public;

grant execute on function public.get_binary_final_result(uuid) to anon, authenticated;
grant execute on function public.get_faction_change_events(uuid) to anon, authenticated;
grant execute on function public.get_post_reaction_counts(uuid) to anon, authenticated;
grant execute on function public.get_superiority_final_result(uuid) to anon, authenticated;
grant execute on function public.get_topic_faction_summary(uuid) to anon, authenticated;
grant execute on function public.get_topic_public_stats(uuid) to anon, authenticated;
grant execute on function public.get_topic_recent_activity(uuid) to anon, authenticated;
grant execute on function public.get_topic_record_summary(uuid) to anon, authenticated;
grant execute on function public.get_topics_public_stats(uuid[]) to anon, authenticated;
grant execute on function public.get_topics_recent_activity(uuid[]) to anon, authenticated;
grant execute on function public.get_werewolf_reveal_pairs(uuid) to anon, authenticated;

-- Authenticated mutations and reads scoped to the current user.
revoke execute on function public.add_my_topic_faction(uuid, uuid) from public, anon;
revoke execute on function public.add_topic_faction(uuid, text) from public, anon;
revoke execute on function public.change_topic_faction(uuid, uuid) from public, anon;
revoke execute on function public.create_post(uuid, text, uuid, text) from public, anon;
revoke execute on function public.create_post(uuid, text, uuid, text, uuid) from public, anon;
revoke execute on function public.create_topic(text, text, text, text, text, timestamptz, text[]) from public, anon;
revoke execute on function public.create_topic_with_rules(text, text, text, text, text, timestamptz, text[], text, integer, boolean, boolean, boolean, boolean, boolean, integer) from public, anon;
revoke execute on function public.get_my_evaluation_requirement(uuid) from public, anon;
revoke execute on function public.get_my_post_reactions(uuid) from public, anon;
revoke execute on function public.get_my_post_usage(uuid) from public, anon;
revoke execute on function public.get_my_topic_factions(uuid) from public, anon;
revoke execute on function public.get_my_werewolf_aliases(uuid) from public, anon;
revoke execute on function public.join_topic(uuid, text, uuid) from public, anon;
revoke execute on function public.join_werewolf_topic(uuid, uuid, uuid, text, uuid, text) from public, anon;
revoke execute on function public.remove_my_topic_faction(uuid, uuid) from public, anon;
revoke execute on function public.remove_post_reaction(uuid) from public, anon;
revoke execute on function public.set_binary_live_vote_counts(uuid, boolean) from public, anon;
revoke execute on function public.set_post_reaction(uuid, text) from public, anon;
revoke execute on function public.set_topic_advanced_rules(uuid, text, integer, boolean) from public, anon;
revoke execute on function public.set_topic_category(uuid, text) from public, anon;
revoke execute on function public.set_werewolf_reveal_mode(uuid, text) from public, anon;

grant execute on function public.add_my_topic_faction(uuid, uuid) to authenticated;
grant execute on function public.add_topic_faction(uuid, text) to authenticated;
grant execute on function public.change_topic_faction(uuid, uuid) to authenticated;
grant execute on function public.create_post(uuid, text, uuid, text) to authenticated;
grant execute on function public.create_post(uuid, text, uuid, text, uuid) to authenticated;
grant execute on function public.create_topic(text, text, text, text, text, timestamptz, text[]) to authenticated;
grant execute on function public.create_topic_with_rules(text, text, text, text, text, timestamptz, text[], text, integer, boolean, boolean, boolean, boolean, boolean, integer) to authenticated;
grant execute on function public.get_my_evaluation_requirement(uuid) to authenticated;
grant execute on function public.get_my_post_reactions(uuid) to authenticated;
grant execute on function public.get_my_post_usage(uuid) to authenticated;
grant execute on function public.get_my_topic_factions(uuid) to authenticated;
grant execute on function public.get_my_werewolf_aliases(uuid) to authenticated;
grant execute on function public.join_topic(uuid, text, uuid) to authenticated;
grant execute on function public.join_werewolf_topic(uuid, uuid, uuid, text, uuid, text) to authenticated;
grant execute on function public.remove_my_topic_faction(uuid, uuid) to authenticated;
grant execute on function public.remove_post_reaction(uuid) to authenticated;
grant execute on function public.set_binary_live_vote_counts(uuid, boolean) to authenticated;
grant execute on function public.set_post_reaction(uuid, text) to authenticated;
grant execute on function public.set_topic_advanced_rules(uuid, text, integer, boolean) to authenticated;
grant execute on function public.set_topic_category(uuid, text) to authenticated;
grant execute on function public.set_werewolf_reveal_mode(uuid, text) to authenticated;

-- Trigger functions, internal helpers, and superseded implementations are not client RPCs.
revoke execute on function public.can_view_binary_vote_counts(uuid) from public, anon, authenticated;
revoke execute on function public.create_post_without_question_20260823(uuid, text, uuid, text, uuid) from public, anon, authenticated;
revoke execute on function public.enforce_fixed_role_faction_count() from public, anon, authenticated;
revoke execute on function public.enforce_new_topic_rule_semantics() from public, anon, authenticated;
revoke execute on function public.enforce_single_faction_membership() from public, anon, authenticated;
revoke execute on function public.enforce_topic_member_primary_faction() from public, anon, authenticated;
revoke execute on function public.ensure_binary_faction_limit() from public, anon, authenticated;
revoke execute on function public.ensure_binary_topic_rules() from public, anon, authenticated;
revoke execute on function public.ensure_debate_type_post_rules() from public, anon, authenticated;
revoke execute on function public.ensure_reaction_allowed_by_topic_rules() from public, anon, authenticated;
revoke execute on function public.ensure_superiority_topic_rules() from public, anon, authenticated;
revoke execute on function public.ensure_topic_open_for_activity() from public, anon, authenticated;
revoke execute on function public.ensure_werewolf_faction_limit() from public, anon, authenticated;
revoke execute on function public.ensure_werewolf_topic_rules() from public, anon, authenticated;
revoke execute on function public.handle_new_user() from public, anon, authenticated;
revoke execute on function public.handle_reaction_points() from public, anon, authenticated;
revoke execute on function public.is_topic_effectively_ended(uuid) from public, anon, authenticated;
revoke execute on function public.recalculate_evaluation_points(uuid) from public, anon, authenticated;
revoke execute on function public.reject_activity_after_effective_end() from public, anon, authenticated;
revoke execute on function public.reject_affiliation_change_after_end() from public, anon, authenticated;
revoke execute on function public.reject_member_faction_change_after_end() from public, anon, authenticated;
revoke execute on function public.set_profile_updated_at() from public, anon, authenticated;
revoke execute on function public.sync_primary_faction_membership() from public, anon, authenticated;
revoke execute on function public.update_superiority_faction_score() from public, anon, authenticated;
revoke execute on function public.update_topic_last_post_at() from public, anon, authenticated;
revoke execute on function public.validate_topic_end_range() from public, anon, authenticated;

grant execute on function public.can_view_binary_vote_counts(uuid) to service_role;
grant execute on function public.create_post_without_question_20260823(uuid, text, uuid, text, uuid) to service_role;
grant execute on function public.enforce_fixed_role_faction_count() to service_role;
grant execute on function public.enforce_new_topic_rule_semantics() to service_role;
grant execute on function public.enforce_single_faction_membership() to service_role;
grant execute on function public.enforce_topic_member_primary_faction() to service_role;
grant execute on function public.ensure_binary_faction_limit() to service_role;
grant execute on function public.ensure_binary_topic_rules() to service_role;
grant execute on function public.ensure_debate_type_post_rules() to service_role;
grant execute on function public.ensure_reaction_allowed_by_topic_rules() to service_role;
grant execute on function public.ensure_superiority_topic_rules() to service_role;
grant execute on function public.ensure_topic_open_for_activity() to service_role;
grant execute on function public.ensure_werewolf_faction_limit() to service_role;
grant execute on function public.ensure_werewolf_topic_rules() to service_role;
grant execute on function public.handle_new_user() to service_role;
grant execute on function public.handle_reaction_points() to service_role;
grant execute on function public.is_topic_effectively_ended(uuid) to service_role;
grant execute on function public.recalculate_evaluation_points(uuid) to service_role;
grant execute on function public.reject_activity_after_effective_end() to service_role;
grant execute on function public.reject_affiliation_change_after_end() to service_role;
grant execute on function public.reject_member_faction_change_after_end() to service_role;
grant execute on function public.set_profile_updated_at() to service_role;
grant execute on function public.sync_primary_faction_membership() to service_role;
grant execute on function public.update_superiority_faction_score() to service_role;
grant execute on function public.update_topic_last_post_at() to service_role;
grant execute on function public.validate_topic_end_range() to service_role;
